version: "3.3"

services:

# ========================
# Application
# ========================

  nginx:
    container_name: nginx_triplink
    build: ./.docker/nginx
    restart: on-failure
    ports:
      - "127.0.0.1:3200:80"
    depends_on:
      - php
    volumes: ["./:/var/www/web:cached"]


  php:
    container_name: php_triplink
    build: ./.docker/php
    restart: on-failure
    volumes: ["./:/var/www/web:cached"]
   

 # ========================
  # MySQL
  # ========================
  mysql:
    image: mysql:5.7
    container_name: mysql_triplink
    env_file:
      - ./.docker/mysql/mysql.env
    volumes:
      - "./.docker/mysql/storage:/var/lib/mysql"
    ports:
      - "127.0.0.1:3306:3306"
