version: "3.3"
networks:
  triplink:
    driver: bridge


services:

# ========================
# Application
# ========================

  nginx:
    container_name: nginx_triplink
    build: ./.docker/nginx
    restart: on-failure
    ports:
      - "3200:80"
    depends_on:
      - php
    volumes: ["./:/var/www/web:cached"]
    networks: ["triplink"]


  php:
    container_name: php_triplink
    build: ./.docker/php
    restart: on-failure
    volumes: ["./:/var/www/web:cached"]
    networks: ["triplink"]
   

 # ========================
  # MySQL
  # ========================
  mysql:
    image: mysql:5.7
    container_name: mysql_triplink
    networks: 
      default:
        aliases: 
          - mysql
          - triplink
    env_file:
      - ./.docker/mysql/mysql.env
    volumes:
      - "./.docker/mysql/storage:/var/lib/mysql"
    ports:
      - "3306:3306"

