version: "3.3"
networks:
  triplink:
    driver: bridge


services:

# ========================
# Application
# ========================

  nginx:
    container_name: nginx_triplink
    build: ./.docker/nginx
    restart: on-failure
    ports:
      - "3200:80"
    depends_on:
      - php
    volumes: ["./:/var/www/web:cached"]
    networks: ["triplink"]


  php:
    container_name: php_triplink
    build: ./.docker/php
    restart: on-failure
    volumes: ["./:/var/www/web:cached"]
    networks: ["triplink"]
   

 # ========================
  # MySQL
  # ========================
  mysql:
    image: mysql:5.7
    container_name: mysql_triplink
    networks: 
      default:
        aliases: 
          - mysql
          - triplink
    env_file:
      - ./.docker/mysql/mysql.env
    volumes:
      - "./.docker/mysql/storage:/var/lib/mysql"
    ports:
      - "3306:3306"


 # ========================
  # Front-React
  # ========================
  react:
    image: node:14-buster-slim
    volumes: ["./front:/usr/src/app"]
    working_dir: /usr/src/app
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - php
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3200
      - HOST=0.0.0.0
      - BROWSER=none
    command: sh -c "yarn install && yarn run start"
    stdin_open: true

