version: "3.3"
networks:
  triplink:
    driver: bridge


services:

# ========================
# Application
# ========================

  nginx:
    container_name: nginx_triplink
    build: ./.docker/nginx
    restart: on-failure
    ports:
      - "3200:80"
    depends_on:
      - php
    volumes: ["./api:/var/www/web:cached"]
    networks: ["triplink"]


  php:
    container_name: php_triplink
    build: ./.docker/php
    restart: on-failure
    volumes: ["./api:/var/www/web:cached"]
    networks: ["triplink"]
   

 # ========================
  # MySQL
  # ========================
  mysql:
    image: mysql:5.7
    container_name: mysql_triplink
    networks: ["triplink"]
    env_file:
      - ./.docker/mysql/mysql.env
    volumes:
      - "./.docker/mysql/storage:/var/lib/mysql"
    ports:
      - "3300:3300"

 # ========================
  # Front-React
  # ========================
  react:
    image: node:14-buster-slim
    volumes: ["./front:/usr/src/app"]
    working_dir: /usr/src/app
    ports:
      - "3100:3100"
    depends_on:
      - php
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:3200
      - HOST=0.0.0.0
      - BROWSER=none
    command: sh -c "yarn install && yarn run start"
    stdin_open: true
    networks: ["triplink"]

