api_platform:
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header