api_platform:

    # The title of the API.
    title: 'API TRIPLINK'

    # The description of the API.
    description: 'API description'

    # The version of the API.
    version: '0.0.0'
     # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']