api_platform:
    resource: .
    type: api_platform
    prefix: /api

app_security_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['POST']
    defaults:
        _api_resource_class: 'App\Entity\User'
        _api_item_operation_name: 'login'
    requirements:
        _format: 'json'

app_security_logout:
    path: /api/logout
    controller: App\Controller\SecurityController::logout
    methods: ['POST']
    defaults:
        _api_resource_class: 'App\Entity\User'
        _api_item_operation_name: 'logout'
    requirements:
        _format: 'json'

user_by_email:
    path: /user/email
    controller: App\Controller\GetUserByEmailController::foundUserByEmail
    methods: ['GET']
    defaults:
        _api_resource_class: 'App\Entity\User'
        _api_operation_name: 'get_user_by_email'
    requirements:
        _format: 'json'